### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Dzmitry-Isayeu** [skaeff/miranda-tester#1]
Добрый день,

Скачал ваш проект, сбилдилось все нормально, однако при запуске выдает такую вот ошибку
![image](https://cloud.githubusercontent.com/assets/18330380/14376964/b5bad474-fd75-11e5-9ccc-f683aa8534f0.png)

Помогите разобраться, спасибо!

**Comment by skaeff** [comment]
привет.

проверьте папку со словарями в output папках - Debug и Release.

Проверьте, что словари лежат рядом с exe в таком порядке:
-- BitmapTester.exe
-- tessdata\eng.traineddata
-- tessdata\rus.traineddata

На будущее - это регулируется тут:
_engineRus = new TesseractEngine(@"./tessdata", "rus", EngineMode.Default);
_engineEng = new TesseractEngine(@"./tessdata", "eng", EngineMode.Default);

Так что можете хранить словари и в других местах.

также проверьте конфиг проекта (Configuration Manager) - надо чтобы все
проекты собирались в x86

8 апреля 2016 г., 10:36 пользователь Dzmitry-Isayeu <
notifications@github.com> написал:

> Добрый день,
> 
> Скачал ваш проект, сбилдилось все номрально, однако при запуске выдает
> такую вот ошибку
> [image: image]
> https://cloud.githubusercontent.com/assets/18330380/14376964/b5bad474-fd75-11e5-9ccc-f683aa8534f0.png
> 
> Помогите разобраться, спасибо!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/skaeff/miranda-tester/issues/1

## 

С уважением, Алексей.
